package sailpoint.service;

import sailpoint.tools.Message;

import java.util.List;

public class UpdateIdentityResultItem extends WorkflowResultItem {
    /* The update identity workflow can easily move an identity out of the requesters quicklink population access
     * if the requester no longer has access to the identity then we return a home outcome otherwise a view identity
     * outcome.  */
    public static enum Outcome {
        HOME,
        VIEW_IDENTITY
    }

    /**
     * Where the client should navigate to.  Defaulting to home because it is a safer default
     */
    private Outcome outcome = Outcome.HOME;

    /**
     * Constructor
     * @param status Resulting workflow status
     * @param requestName The request name
     * @param workItemType Type of the next work item in the workflow
     * @param workItemId Id of the next work item in the workflow
     * @param messages Any messages that were generated by the workflow
     */
    public UpdateIdentityResultItem(String status, String requestName, String workItemType, String workItemId, List<Message> messages) {
        super(status, requestName, workItemType, workItemId, messages);
    }

    /**
     * Sets the outcome
     * @param outcome The outcome
     */
    public void setOutcome(Outcome outcome) {
        this.outcome = outcome;
    }

    /**
     * Returns the outcome
     * @return The outcome
     */
    public Outcome getOutcome() {
        return outcome;
    }
}
