package sp.poc.filter;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;

import sp.poc.filter.CharResponseWrapper;
import sp.poc.filter.ResponseFilter;
public class onetwo {

	public static void main(String[] args)  {
		// TODO Auto-generated method stub	
		rrrr rf = new rrrr();
		System.out.println("Hellowordlll");
		
		String s = "<!DOCTYPE html>\n"
				+ "<!-- (c) Copyright 2008 SailPoint Technologies, Inc., All Rights Reserved. --><html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
				+ "<body>\n"
				+ "  <table border=\"0\" style=\"table-layout:auto;\">\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">costcenter\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">L07e</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>L07e </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">R03e</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>R03e </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">department\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">Information Technology</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>Information Technology </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">email\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">Lisa.Rodriguez@demoexample.com</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>Lisa.Rodriguez@demoexample.com </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">employeeId\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">1a2a3b4a</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>1a2a3b4a </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">firstName\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">Lisa</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>Lisa </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">fullName\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">Lisa.Rodriguez</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>Lisa.Rodriguez </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">inactiveIdentity\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">FALSE</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>FALSE </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">jobtitle\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">Information Security Analyst</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>Information Security Analyst </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">lastName\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">Rodriguez</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>Rodriguez </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">location\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">Austin</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>Austin </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">managerId\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">1a2a3b</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>1a2a3b </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "      <tr>\n"
				+ "        <td style=\"padding: 2px; padding-right: 5px; padding-top:3px; font-weight:bold\" class=\"title\" valign=\"top\">region\n"
				+ "        </td>\n"
				+ "        <td style=\"padding: 2px\" class=\"wide\">\n"
				+ "          <table>\n"
				+ "              <tr><td style=\"padding: 0px;\" valign=\"top\">\n"
				+ "                  <span>\n"
				+ "  <span><span style=\"word-break: break-word;\">Americas</span>  \n"
				+ "  </span>\n"
				+ "  \n"
				+ "  <span class=\"entitlementDescriptionsSpan\">\n"
				+ "    \n"
				+ "    <span class=\"descriptionText\" style=\"display:none\"><span>Americas </span></span>\n"
				+ "  </span>\n"
				+ "                  </span>\n"
				+ "              </td></tr>\n"
				+ "          </table>\n"
				+ "        </td>\n"
				+ "      </tr>\n"
				+ "  </table>\n"
				+ "</body>\n"
				+ "</html>";
		
		List attributesToHide = new ArrayList();
		attributesToHide.add("email");
		attributesToHide.add("location");
		attributesToHide.add("department");
		
		try {
			rf.tempCode( s,  attributesToHide);
		} catch (ServletException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
