/* (c) Copyright 2008 SailPoint Technologies, Inc., All Rights Reserved. */
package sailpoint.reporting;

import sailpoint.object.Filter;

/**
 * Implemented by report parameter classes that know
 * how to build thier own filter.
 * @author jonathan.bryant@sailpoint.com
 */
public interface FilterParameter {

    /**
     * Returns the filter generated by this parameter. May be null
     */
    Filter getFilter();

}
